sonar.organization=i-am-dheerajkadve
sonar.projectKey=i-am-dheerajkadve_sonar-scan
sonar.projectName=devops-frontend

sonar.sources=frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.git/**,**/coverage/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
