name: Frontend CI Security Scan and Push to ECR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write


jobs:
  scan-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4

      # 1. SonarQube/SonarCloud source code scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
